<?php

/**
 * @copyright	Copyright (c) 2015 - 2016
* @license		https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
* @author		Mulot
* @link		http://life.je.gfns.ru/
* @version		0.1 alpha
* @since		File available since 0.1 alpha
*/

$this->headTitle('Version');
?>
<div class="row">
	<div class="col-xs-6 col-sm-3 col-md-2"><p>0.1 beta</p></div>
	<div class="col-xs-6 col-sm-9 col-md-10">
		<p>Published on 01-24-2017</p>
		<ul>
			<li>First beta release</li>
		</ul>
	</div>
</div>