<?php

/**
 * @copyright	Copyright (c) 2015 - 2016
* @license		https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
* @author		Mulot
* @link		http://life.je.gfns.ru/
* @version		0.1 alpha
* @since		File available since 0.1 alpha
*/

$this->headTitle('Version');
?>
<?php foreach ($versions as $version): ?>
	<div class="row">
		<div class="col-xs-6 col-sm-3 col-md-2"><p><?= $version['version'] ?></p></div>
		<div class="col-xs-6 col-sm-9 col-md-10">
			<p><i>Released on <?= $version['date'] ?></i></p>
			<ul>
				<?php foreach ($version['fixed'] as $fixed): ?>
					<li><?= $fixed ?></li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
	<br />
<?php endforeach; ?>