<?php

/**
 * @copyright	Copyright (c) 2015 - 2016
* @license		https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
* @author		Mulot
* @link		http://life.je.gfns.ru/
* @version		0.1 alpha
* @since		File available since 0.1 alpha
*/

$this->headTitle('USER_NEW_ACCOUNT');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'USER_NEW_ACCOUNT_MAIL_PLACEHOLDER'
    ]);

$form->get('full_name')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'USER_NEW_ACCOUNT_NAME_PLACEHOLDER'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('confirm_password')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('language')->setAttributes([
		'class'=>'form-control selectpicker'
]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>
<p></p>
<p>
    <?= $this->translate('USER_NEW_ACCOUNT_TEXT')?>
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
		
		<div class="form-group">
            <?= $this->formLabel($form->get('full_name')); ?>
            <?= $this->formElement($form->get('full_name')); ?>
            <?= $this->formElementErrors($form->get('full_name')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>                  
        </div>
                
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>                  
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('language')); ?> 
            <?= $this->formElement($form->get('language')); ?>
            <?= $this->formElementErrors($form->get('language')); ?>                  
        </div>

        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

