<?php

/**
 * @copyright	Copyright (c) 2015 - 2016
* @license		https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
* @author		Mulot
* @link		http://life.je.gfns.ru/
* @version		0.1 alpha
* @since		File available since 0.1 alpha
*/

$this->headTitle('USER_RESET_PASSWORD');

$form->get('email')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'USER_MAIL'
    ]);

$form->get('submit')->setAttributes([
    'class'=>'btn btn-large btn-primary'
    ]);

$form->prepare();
?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

        <h2><?= $this->translate('USER_RESET_PASSWORD')?></h2>

        <p><?= $this->translate('USER_RESET_PASSWORD_TEXT')?></p>

        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint"><?= $this->translate('USER_CAPTCHA_TEXT')?></p>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
