<?php

/**
 * @copyright	Copyright (c) 2015 - 2016
* @license		https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
* @author		Mulot
* @link		http://life.je.gfns.ru/
* @version		0.1 alpha
* @since		File available since 0.1 alpha
*/

$this->headTitle('ADD');

$form->get('food')->setAttributes([
    	'class'=>'form-control selectpicker', 
]);
$form->get('quantity')->setAttributes([
	    'class'=>'form-control', 
	    'placeholder'=>$this->translate('WASTE_QUANTITY'),
]);

$form->get('UOM')->setAttributes([
		'class'=>'form-control selectpicker',
]);

$form->get('why')->setAttributes([
		'class'=>'form-control',
		'placeholder'=>$this->translate('WASTE_WHY'),
]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>
<script type="text/javascript">
	var foods = [];
	<?php foreach ($foods as $food): ?>
		foods[<?= $food->getId()?>] =  <?= $food->getWeight(); ?>;
	<?php endforeach; ?>

	function calculateWeight() {
		if ($("select[name=UOM]").val() == 'Unit' && $.isNumeric($("input[name=quantity]").val()) && $("input[name=quantity]").val() != 0) {
			$("#weight").text("Soit " + foods[$("select[name=food]").val()] * $("input[name=quantity]").val() + " g");
		} else {
			$("#weight").text("");
		}
	}

	$(document).ready(function() {
		$("select[name=food]").change(function() {
			if (foods[$(this).val()] == 0) {
				$("select[name=UOM]").find('[value=Unit]').prop('disabled', true);
				$("select[name=UOM]").val('kg');
				calculateWeight();
			} else {
				$("select[name=UOM]").find('[value=Unit]').prop('disabled', false);
			}
			$("select[name=UOM]").selectpicker('refresh');
		});
		$("select[name=food]").change();
		
		$("input[name=quantity]").change(calculateWeight);
		$("select[name=UOM]").change(calculateWeight);
	});
</script>
<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('food')); ?>
            <?= $this->formElement($form->get('food')); ?>
            <?= $this->formElementErrors($form->get('food')); ?>                  
        </div>
        
        <div class="form-group">
        	<?= $this->formLabel($form->get('quantity')); ?>
        	<div class="row">
		        <div class="col-md-6">
		        	<?= $this->formElement($form->get('quantity')); ?>
				</div>
				<div class="col-md-6">
					<?= $this->formElement($form->get('UOM')); ?>
				</div>
        	</div>
        	<div class="row">
		        <div class="col-md-6">
		        	<?= $this->formElementErrors($form->get('quantity')); ?>
				</div>
				<div class="col-md-6">
					<?= $this->formElementErrors($form->get('UOM')); ?>
				</div>
        	</div>
        	<br />
        	<p id="weight"></p>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('why')); ?>
            <?= $this->formElement($form->get('why')); ?>
            <?= $this->formElementErrors($form->get('why')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div> 