<?php 

/**
 * @copyright	Copyright (c) 2015 - 2016
 * @license		https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
 * @author		Mulot
 * @link		http://life.je.gfns.ru/
 * @version		0.1 alpha
 * @since		File available since 0.1 alpha
 */

?>
<h1>&nbsp;</h1>
<div class="row">
	<div class="col-md-offset-4 col-md-3">
		<a class="btn btn-lg btn-primary btn-block" href="<?= $this->url('admin/food'); ?>">
			<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> Gérer la liste de nourriture
		</a>
		<h5>&nbsp;</h5>
		<a class="btn btn-lg btn-primary btn-block" href="<?= $this->url('posts', ['action'=>'admin']); ?>">
			<span class="glyphicon glyphicon-book" aria-hidden="true"></span> Gérer le blog
		</a>
		<h5>&nbsp;</h5>
		<a class="btn btn-lg btn-primary btn-block" href="<?= $this->url('admin/users'); ?>">
			<span class="glyphicon glyphicon-user" aria-hidden="true"></span> Gérer les utilisateurs
		</a>
	</div>
</div>